#!/usr/local/bin/php
<?php

$pages = json_decode(file_get_contents("pages.json"));

if (!file_exists("newsite")) mkdir("newsite");

foreach ($pages as $page) {
    $out = "";
    print "Working on {$page->title}\n";
    foreach ($page->templates as $tpl) {
        $out .= preg_replace_callback("/\%\%(.+?)\%\%/", function($m) {
            global $page;
            if (isset($page->{$m[1]})) {
                return $page->{$m[1]};
            } else {
                return "";
            }
        }, file_get_contents("{$tpl}")); 
        print "\tAdded $tpl\n";
    }
    
    $dir = dirname($page->file);
    if (!file_exists("newsite/".$dir)) {
        mkdir("newsite/".$dir);
    }
    file_put_contents("newsite/" . $page->file, $out);
    print "Created {$page->file} [".strlen($out)." bytes]\n";

}
